import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import { QueryProvider } from "@/components/providers/QueryProvider";

import { AuthProvider } from "@/components/providers/AuthProvider";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={cn("dark font-sans", geist.variable)}>
            <body className="antialiased flex flex-col min-h-screen">
                <QueryProvider>
                    <AuthProvider>

                        <Navbar />
                        <div className="flex-1">{children}</div>
                        <Footer />
                    </AuthProvider>
                </QueryProvider>
            </body>
        </html>
    )
}
